<a href="https://colab.research.google.com/github/Twujira/TigistData110/blob/main/Markov_Chain.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

As a child, I used to bet with my siblings every night on who would host the evening news. The prime time news began streaming at 8:00 pm on Ethiopia's national TV, Ethiopian Television (ETV). There were three well-known hosts who took turns leading the news, but it was impossible to predict who would be on air that evening.

Their name is Hermela, Amare, and Temesgen

Transaction Matrix:

     Hermela | Amare | Temesgen
    H|  0.7  | 0.2   |  0.1
    A|  0.3  | 0.5   |  0.2
    T|  0.2  | 0.2   |  0.6



In [14]:
#Import necessary packages
from sympy import Matrix
import numpy as np

In [59]:
# Define the transition matrix
T_host = np.array([
    [0.7, 0.2, 0.1],
    [0.3, 0.5, 0.2],
    [0.2, 0.2, 0.6]
])

# Print the transition matrix
print(T_host)


[[0.7 0.2 0.1]
 [0.3 0.5 0.2]
 [0.2 0.2 0.6]]


As an initial state, if the host were Hermela. v= [1,0,0]

In [57]:
# Define the initial state vector
V0 = np.array([1, 0, 0])

# Multiply the initial state vector with the transition matrix
V1 =T_host * V0

# Print the result
print(V1)


[[0.700000000000000 0 0]
 [0.300000000000000 0 0]
 [0.200000000000000 0 0]]


For Day2

In [60]:
#multiply day1 result with transition matrix
V2= T_host* V1
print(V2)

[[0.490000000000000 0 0]
 [0.0900000000000000 0 0]
 [0.0400000000000000 0 0]]


For Day3

In [61]:
#multiply day2 result with transition matrix
V3= T_host * V2
print(V3)

[[0.343000000000000 0 0]
 [0.0270000000000000 0 0]
 [0.00800000000000000 0 0]]


## Activity 2

Given 2022 Population

x0=

    [600,000]

    [400,000]

In [62]:
#Define transax matrix
A = np.array([
    [0.92,0.04],
    [0.08,0.96]
    ])
print(A)



[[0.92 0.04]
 [0.08 0.96]]


In [63]:
#Initial 2022 population
x0 = np.array([
    [600000],
    [400000]
])
print(x0)

[[600000]
 [400000]]


## 1. For 2023

In [72]:
#Population predict 2023

P_2023=A*x0
print(P_2023)

[[552000.  24000.]
 [ 32000. 384000.]]


## 2. For 2030

P2030= A^22*x0

In [73]:
A = np.array([[0.92, 0.04], [0.08, 0.96]])
A_22 = np.linalg.matrix_power(A, 22)
print(A_22)

[[0.37337642 0.31331179]
 [0.62662358 0.68668821]]


In [74]:
P_2030=A_22*x0
print(P_2030)

[[224025.85095737 187987.07452132]
 [250649.43269509 274675.28365246]]
